[package]
name = "wordle_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bencher = "0.1.5"
itertools = "0.10.3"
once_cell = "1.13.0"
[profile.release] 
debug = true
depth = 3
